sonar.organization=totolouis
sonar.projectKey=totolouis_SimplyFiles

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.js,**/*.test.jsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.e2e.spec.ts

sonar.coverage.exclusions=**/migrations/**,**/main.ts,**/index.js,**/app.module.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
